# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.checkpointing_statistics_summary import CheckpointingStatisticsSummary  # noqa: E501
from swagger_client.rest import ApiException


class TestCheckpointingStatisticsSummary(unittest.TestCase):
    """CheckpointingStatisticsSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckpointingStatisticsSummary(self):
        """Test CheckpointingStatisticsSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.checkpointing_statistics_summary.CheckpointingStatisticsSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
