# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.subtask_execution_attempt_details_info import SubtaskExecutionAttemptDetailsInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestSubtaskExecutionAttemptDetailsInfo(unittest.TestCase):
    """SubtaskExecutionAttemptDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtaskExecutionAttemptDetailsInfo(self):
        """Test SubtaskExecutionAttemptDetailsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subtask_execution_attempt_details_info.SubtaskExecutionAttemptDetailsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
