# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.job_vertex_accumulators_info import JobVertexAccumulatorsInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestJobVertexAccumulatorsInfo(unittest.TestCase):
    """JobVertexAccumulatorsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobVertexAccumulatorsInfo(self):
        """Test JobVertexAccumulatorsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.job_vertex_accumulators_info.JobVertexAccumulatorsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
