# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.subtasks_all_accumulators_info import SubtasksAllAccumulatorsInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestSubtasksAllAccumulatorsInfo(unittest.TestCase):
    """SubtasksAllAccumulatorsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtasksAllAccumulatorsInfo(self):
        """Test SubtasksAllAccumulatorsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subtasks_all_accumulators_info.SubtasksAllAccumulatorsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
