# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.trigger_response import TriggerResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestTriggerResponse(unittest.TestCase):
    """TriggerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTriggerResponse(self):
        """Test TriggerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trigger_response.TriggerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
