# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.cluster_configuration_info_entry import ClusterConfigurationInfoEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestClusterConfigurationInfoEntry(unittest.TestCase):
    """ClusterConfigurationInfoEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterConfigurationInfoEntry(self):
        """Test ClusterConfigurationInfoEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cluster_configuration_info_entry.ClusterConfigurationInfoEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
