# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.task_manager_details_info import TaskManagerDetailsInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskManagerDetailsInfo(unittest.TestCase):
    """TaskManagerDetailsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskManagerDetailsInfo(self):
        """Test TaskManagerDetailsInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_manager_details_info.TaskManagerDetailsInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
