# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.task_checkpoint_statistics_with_subtask_details import TaskCheckpointStatisticsWithSubtaskDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskCheckpointStatisticsWithSubtaskDetails(unittest.TestCase):
    """TaskCheckpointStatisticsWithSubtaskDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskCheckpointStatisticsWithSubtaskDetails(self):
        """Test TaskCheckpointStatisticsWithSubtaskDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_checkpoint_statistics_with_subtask_details.TaskCheckpointStatisticsWithSubtaskDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
