# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.jar_plan_request_body import JarPlanRequestBody  # noqa: E501
from swagger_client.rest import ApiException


class TestJarPlanRequestBody(unittest.TestCase):
    """JarPlanRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJarPlanRequestBody(self):
        """Test JarPlanRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jar_plan_request_body.JarPlanRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
