# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.task_managers_info import TaskManagersInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskManagersInfo(unittest.TestCase):
    """TaskManagersInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskManagersInfo(self):
        """Test TaskManagersInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_managers_info.TaskManagersInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
