# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.distributed_cache_file import DistributedCacheFile  # noqa: E501
from swagger_client.rest import ApiException


class TestDistributedCacheFile(unittest.TestCase):
    """DistributedCacheFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistributedCacheFile(self):
        """Test DistributedCacheFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.distributed_cache_file.DistributedCacheFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
