# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.jar_entry_info import JarEntryInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestJarEntryInfo(unittest.TestCase):
    """JarEntryInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJarEntryInfo(self):
        """Test JarEntryInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jar_entry_info.JarEntryInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
