# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.dashboard_configuration import DashboardConfiguration  # noqa: E501
from swagger_client.rest import ApiException


class TestDashboardConfiguration(unittest.TestCase):
    """DashboardConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDashboardConfiguration(self):
        """Test DashboardConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dashboard_configuration.DashboardConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
