# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.job_ids_with_status_overview import JobIdsWithStatusOverview  # noqa: E501
from swagger_client.rest import ApiException


class TestJobIdsWithStatusOverview(unittest.TestCase):
    """JobIdsWithStatusOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobIdsWithStatusOverview(self):
        """Test JobIdsWithStatusOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.job_ids_with_status_overview.JobIdsWithStatusOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
