# coding: utf-8

"""
    Flink Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.cluster_overview_with_version import ClusterOverviewWithVersion  # noqa: E501
from swagger_client.rest import ApiException


class TestClusterOverviewWithVersion(unittest.TestCase):
    """ClusterOverviewWithVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterOverviewWithVersion(self):
        """Test ClusterOverviewWithVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cluster_overview_with_version.ClusterOverviewWithVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
