# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CheckpointingStatisticsSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state_size': 'MinMaxAvgStatistics',
        'end_to_end_duration': 'MinMaxAvgStatistics',
        'alignment_buffered': 'MinMaxAvgStatistics'
    }

    attribute_map = {
        'state_size': 'state_size',
        'end_to_end_duration': 'end_to_end_duration',
        'alignment_buffered': 'alignment_buffered'
    }

    def __init__(self, state_size=None, end_to_end_duration=None, alignment_buffered=None):  # noqa: E501
        """CheckpointingStatisticsSummary - a model defined in Swagger"""  # noqa: E501
        self._state_size = None
        self._end_to_end_duration = None
        self._alignment_buffered = None
        self.discriminator = None
        if state_size is not None:
            self.state_size = state_size
        if end_to_end_duration is not None:
            self.end_to_end_duration = end_to_end_duration
        if alignment_buffered is not None:
            self.alignment_buffered = alignment_buffered

    @property
    def state_size(self):
        """Gets the state_size of this CheckpointingStatisticsSummary.  # noqa: E501


        :return: The state_size of this CheckpointingStatisticsSummary.  # noqa: E501
        :rtype: MinMaxAvgStatistics
        """
        return self._state_size

    @state_size.setter
    def state_size(self, state_size):
        """Sets the state_size of this CheckpointingStatisticsSummary.


        :param state_size: The state_size of this CheckpointingStatisticsSummary.  # noqa: E501
        :type: MinMaxAvgStatistics
        """

        self._state_size = state_size

    @property
    def end_to_end_duration(self):
        """Gets the end_to_end_duration of this CheckpointingStatisticsSummary.  # noqa: E501


        :return: The end_to_end_duration of this CheckpointingStatisticsSummary.  # noqa: E501
        :rtype: MinMaxAvgStatistics
        """
        return self._end_to_end_duration

    @end_to_end_duration.setter
    def end_to_end_duration(self, end_to_end_duration):
        """Sets the end_to_end_duration of this CheckpointingStatisticsSummary.


        :param end_to_end_duration: The end_to_end_duration of this CheckpointingStatisticsSummary.  # noqa: E501
        :type: MinMaxAvgStatistics
        """

        self._end_to_end_duration = end_to_end_duration

    @property
    def alignment_buffered(self):
        """Gets the alignment_buffered of this CheckpointingStatisticsSummary.  # noqa: E501


        :return: The alignment_buffered of this CheckpointingStatisticsSummary.  # noqa: E501
        :rtype: MinMaxAvgStatistics
        """
        return self._alignment_buffered

    @alignment_buffered.setter
    def alignment_buffered(self, alignment_buffered):
        """Sets the alignment_buffered of this CheckpointingStatisticsSummary.


        :param alignment_buffered: The alignment_buffered of this CheckpointingStatisticsSummary.  # noqa: E501
        :type: MinMaxAvgStatistics
        """

        self._alignment_buffered = alignment_buffered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckpointingStatisticsSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckpointingStatisticsSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
