# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CheckpointingStatisticsLatestCheckpoints(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completed': 'CompletedCheckpointStatistics',
        'savepoint': 'CompletedCheckpointStatistics',
        'failed': 'FailedCheckpointStatistics',
        'restored': 'RestoredCheckpointStatistics'
    }

    attribute_map = {
        'completed': 'completed',
        'savepoint': 'savepoint',
        'failed': 'failed',
        'restored': 'restored'
    }

    def __init__(self, completed=None, savepoint=None, failed=None, restored=None):  # noqa: E501
        """CheckpointingStatisticsLatestCheckpoints - a model defined in Swagger"""  # noqa: E501
        self._completed = None
        self._savepoint = None
        self._failed = None
        self._restored = None
        self.discriminator = None
        if completed is not None:
            self.completed = completed
        if savepoint is not None:
            self.savepoint = savepoint
        if failed is not None:
            self.failed = failed
        if restored is not None:
            self.restored = restored

    @property
    def completed(self):
        """Gets the completed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501


        :return: The completed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :rtype: CompletedCheckpointStatistics
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this CheckpointingStatisticsLatestCheckpoints.


        :param completed: The completed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :type: CompletedCheckpointStatistics
        """

        self._completed = completed

    @property
    def savepoint(self):
        """Gets the savepoint of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501


        :return: The savepoint of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :rtype: CompletedCheckpointStatistics
        """
        return self._savepoint

    @savepoint.setter
    def savepoint(self, savepoint):
        """Sets the savepoint of this CheckpointingStatisticsLatestCheckpoints.


        :param savepoint: The savepoint of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :type: CompletedCheckpointStatistics
        """

        self._savepoint = savepoint

    @property
    def failed(self):
        """Gets the failed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501


        :return: The failed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :rtype: FailedCheckpointStatistics
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this CheckpointingStatisticsLatestCheckpoints.


        :param failed: The failed of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :type: FailedCheckpointStatistics
        """

        self._failed = failed

    @property
    def restored(self):
        """Gets the restored of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501


        :return: The restored of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :rtype: RestoredCheckpointStatistics
        """
        return self._restored

    @restored.setter
    def restored(self, restored):
        """Sets the restored of this CheckpointingStatisticsLatestCheckpoints.


        :param restored: The restored of this CheckpointingStatisticsLatestCheckpoints.  # noqa: E501
        :type: RestoredCheckpointStatistics
        """

        self._restored = restored

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckpointingStatisticsLatestCheckpoints, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckpointingStatisticsLatestCheckpoints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
