# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ExecutionExceptionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exception': 'str',
        'task': 'str',
        'location': 'str',
        'timestamp': 'int'
    }

    attribute_map = {
        'exception': 'exception',
        'task': 'task',
        'location': 'location',
        'timestamp': 'timestamp'
    }

    def __init__(self, exception=None, task=None, location=None, timestamp=None):  # noqa: E501
        """ExecutionExceptionInfo - a model defined in Swagger"""  # noqa: E501
        self._exception = None
        self._task = None
        self._location = None
        self._timestamp = None
        self.discriminator = None
        if exception is not None:
            self.exception = exception
        if task is not None:
            self.task = task
        if location is not None:
            self.location = location
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def exception(self):
        """Gets the exception of this ExecutionExceptionInfo.  # noqa: E501


        :return: The exception of this ExecutionExceptionInfo.  # noqa: E501
        :rtype: str
        """
        return self._exception

    @exception.setter
    def exception(self, exception):
        """Sets the exception of this ExecutionExceptionInfo.


        :param exception: The exception of this ExecutionExceptionInfo.  # noqa: E501
        :type: str
        """

        self._exception = exception

    @property
    def task(self):
        """Gets the task of this ExecutionExceptionInfo.  # noqa: E501


        :return: The task of this ExecutionExceptionInfo.  # noqa: E501
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this ExecutionExceptionInfo.


        :param task: The task of this ExecutionExceptionInfo.  # noqa: E501
        :type: str
        """

        self._task = task

    @property
    def location(self):
        """Gets the location of this ExecutionExceptionInfo.  # noqa: E501


        :return: The location of this ExecutionExceptionInfo.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this ExecutionExceptionInfo.


        :param location: The location of this ExecutionExceptionInfo.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def timestamp(self):
        """Gets the timestamp of this ExecutionExceptionInfo.  # noqa: E501


        :return: The timestamp of this ExecutionExceptionInfo.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ExecutionExceptionInfo.


        :param timestamp: The timestamp of this ExecutionExceptionInfo.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionExceptionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionExceptionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
