# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GarbageCollectorInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'count': 'int',
        'time': 'int'
    }

    attribute_map = {
        'name': 'name',
        'count': 'count',
        'time': 'time'
    }

    def __init__(self, name=None, count=None, time=None):  # noqa: E501
        """GarbageCollectorInfo - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._count = None
        self._time = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if count is not None:
            self.count = count
        if time is not None:
            self.time = time

    @property
    def name(self):
        """Gets the name of this GarbageCollectorInfo.  # noqa: E501


        :return: The name of this GarbageCollectorInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GarbageCollectorInfo.


        :param name: The name of this GarbageCollectorInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def count(self):
        """Gets the count of this GarbageCollectorInfo.  # noqa: E501


        :return: The count of this GarbageCollectorInfo.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this GarbageCollectorInfo.


        :param count: The count of this GarbageCollectorInfo.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def time(self):
        """Gets the time of this GarbageCollectorInfo.  # noqa: E501


        :return: The time of this GarbageCollectorInfo.  # noqa: E501
        :rtype: int
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this GarbageCollectorInfo.


        :param time: The time of this GarbageCollectorInfo.  # noqa: E501
        :type: int
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GarbageCollectorInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GarbageCollectorInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
