# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class JarRunRequestBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entry_class': 'str',
        'program_args': 'str',
        'program_args_list': 'list[str]',
        'parallelism': 'int',
        'allow_non_restored_state': 'bool',
        'savepoint_path': 'str'
    }

    attribute_map = {
        'entry_class': 'entryClass',
        'program_args': 'programArgs',
        'program_args_list': 'programArgsList',
        'parallelism': 'parallelism',
        'allow_non_restored_state': 'allowNonRestoredState',
        'savepoint_path': 'savepointPath'
    }

    def __init__(self, entry_class=None, program_args=None, program_args_list=None, parallelism=None, allow_non_restored_state=None, savepoint_path=None):  # noqa: E501
        """JarRunRequestBody - a model defined in Swagger"""  # noqa: E501
        self._entry_class = None
        self._program_args = None
        self._program_args_list = None
        self._parallelism = None
        self._allow_non_restored_state = None
        self._savepoint_path = None
        self.discriminator = None
        if entry_class is not None:
            self.entry_class = entry_class
        if program_args is not None:
            self.program_args = program_args
        if program_args_list is not None:
            self.program_args_list = program_args_list
        if parallelism is not None:
            self.parallelism = parallelism
        if allow_non_restored_state is not None:
            self.allow_non_restored_state = allow_non_restored_state
        if savepoint_path is not None:
            self.savepoint_path = savepoint_path

    @property
    def entry_class(self):
        """Gets the entry_class of this JarRunRequestBody.  # noqa: E501


        :return: The entry_class of this JarRunRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._entry_class

    @entry_class.setter
    def entry_class(self, entry_class):
        """Sets the entry_class of this JarRunRequestBody.


        :param entry_class: The entry_class of this JarRunRequestBody.  # noqa: E501
        :type: str
        """

        self._entry_class = entry_class

    @property
    def program_args(self):
        """Gets the program_args of this JarRunRequestBody.  # noqa: E501


        :return: The program_args of this JarRunRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._program_args

    @program_args.setter
    def program_args(self, program_args):
        """Sets the program_args of this JarRunRequestBody.


        :param program_args: The program_args of this JarRunRequestBody.  # noqa: E501
        :type: str
        """

        self._program_args = program_args

    @property
    def program_args_list(self):
        """Gets the program_args_list of this JarRunRequestBody.  # noqa: E501


        :return: The program_args_list of this JarRunRequestBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._program_args_list

    @program_args_list.setter
    def program_args_list(self, program_args_list):
        """Sets the program_args_list of this JarRunRequestBody.


        :param program_args_list: The program_args_list of this JarRunRequestBody.  # noqa: E501
        :type: list[str]
        """

        self._program_args_list = program_args_list

    @property
    def parallelism(self):
        """Gets the parallelism of this JarRunRequestBody.  # noqa: E501


        :return: The parallelism of this JarRunRequestBody.  # noqa: E501
        :rtype: int
        """
        return self._parallelism

    @parallelism.setter
    def parallelism(self, parallelism):
        """Sets the parallelism of this JarRunRequestBody.


        :param parallelism: The parallelism of this JarRunRequestBody.  # noqa: E501
        :type: int
        """

        self._parallelism = parallelism

    @property
    def allow_non_restored_state(self):
        """Gets the allow_non_restored_state of this JarRunRequestBody.  # noqa: E501


        :return: The allow_non_restored_state of this JarRunRequestBody.  # noqa: E501
        :rtype: bool
        """
        return self._allow_non_restored_state

    @allow_non_restored_state.setter
    def allow_non_restored_state(self, allow_non_restored_state):
        """Sets the allow_non_restored_state of this JarRunRequestBody.


        :param allow_non_restored_state: The allow_non_restored_state of this JarRunRequestBody.  # noqa: E501
        :type: bool
        """

        self._allow_non_restored_state = allow_non_restored_state

    @property
    def savepoint_path(self):
        """Gets the savepoint_path of this JarRunRequestBody.  # noqa: E501


        :return: The savepoint_path of this JarRunRequestBody.  # noqa: E501
        :rtype: str
        """
        return self._savepoint_path

    @savepoint_path.setter
    def savepoint_path(self, savepoint_path):
        """Sets the savepoint_path of this JarRunRequestBody.


        :param savepoint_path: The savepoint_path of this JarRunRequestBody.  # noqa: E501
        :type: str
        """

        self._savepoint_path = savepoint_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JarRunRequestBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JarRunRequestBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
