# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class JobVertexBackPressureInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'backpressure_level': 'str',
        'end_timestamp': 'int',
        'subtasks': 'list[SubtaskBackPressureInfo]'
    }

    attribute_map = {
        'status': 'status',
        'backpressure_level': 'backpressure-level',
        'end_timestamp': 'end-timestamp',
        'subtasks': 'subtasks'
    }

    def __init__(self, status=None, backpressure_level=None, end_timestamp=None, subtasks=None):  # noqa: E501
        """JobVertexBackPressureInfo - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._backpressure_level = None
        self._end_timestamp = None
        self._subtasks = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if backpressure_level is not None:
            self.backpressure_level = backpressure_level
        if end_timestamp is not None:
            self.end_timestamp = end_timestamp
        if subtasks is not None:
            self.subtasks = subtasks

    @property
    def status(self):
        """Gets the status of this JobVertexBackPressureInfo.  # noqa: E501


        :return: The status of this JobVertexBackPressureInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this JobVertexBackPressureInfo.


        :param status: The status of this JobVertexBackPressureInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["deprecated", "ok"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def backpressure_level(self):
        """Gets the backpressure_level of this JobVertexBackPressureInfo.  # noqa: E501


        :return: The backpressure_level of this JobVertexBackPressureInfo.  # noqa: E501
        :rtype: str
        """
        return self._backpressure_level

    @backpressure_level.setter
    def backpressure_level(self, backpressure_level):
        """Sets the backpressure_level of this JobVertexBackPressureInfo.


        :param backpressure_level: The backpressure_level of this JobVertexBackPressureInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["ok", "low", "high"]  # noqa: E501
        if backpressure_level not in allowed_values:
            raise ValueError(
                "Invalid value for `backpressure_level` ({0}), must be one of {1}"  # noqa: E501
                .format(backpressure_level, allowed_values)
            )

        self._backpressure_level = backpressure_level

    @property
    def end_timestamp(self):
        """Gets the end_timestamp of this JobVertexBackPressureInfo.  # noqa: E501


        :return: The end_timestamp of this JobVertexBackPressureInfo.  # noqa: E501
        :rtype: int
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp):
        """Sets the end_timestamp of this JobVertexBackPressureInfo.


        :param end_timestamp: The end_timestamp of this JobVertexBackPressureInfo.  # noqa: E501
        :type: int
        """

        self._end_timestamp = end_timestamp

    @property
    def subtasks(self):
        """Gets the subtasks of this JobVertexBackPressureInfo.  # noqa: E501


        :return: The subtasks of this JobVertexBackPressureInfo.  # noqa: E501
        :rtype: list[SubtaskBackPressureInfo]
        """
        return self._subtasks

    @subtasks.setter
    def subtasks(self, subtasks):
        """Sets the subtasks of this JobVertexBackPressureInfo.


        :param subtasks: The subtasks of this JobVertexBackPressureInfo.  # noqa: E501
        :type: list[SubtaskBackPressureInfo]
        """

        self._subtasks = subtasks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobVertexBackPressureInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobVertexBackPressureInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
