# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class JobAccumulatorsInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_accumulators': 'list[object]',
        'user_task_accumulators': 'list[UserTaskAccumulator]',
        'serialized_user_task_accumulators': 'dict(str, object)'
    }

    attribute_map = {
        'job_accumulators': 'job-accumulators',
        'user_task_accumulators': 'user-task-accumulators',
        'serialized_user_task_accumulators': 'serialized-user-task-accumulators'
    }

    def __init__(self, job_accumulators=None, user_task_accumulators=None, serialized_user_task_accumulators=None):  # noqa: E501
        """JobAccumulatorsInfo - a model defined in Swagger"""  # noqa: E501
        self._job_accumulators = None
        self._user_task_accumulators = None
        self._serialized_user_task_accumulators = None
        self.discriminator = None
        if job_accumulators is not None:
            self.job_accumulators = job_accumulators
        if user_task_accumulators is not None:
            self.user_task_accumulators = user_task_accumulators
        if serialized_user_task_accumulators is not None:
            self.serialized_user_task_accumulators = serialized_user_task_accumulators

    @property
    def job_accumulators(self):
        """Gets the job_accumulators of this JobAccumulatorsInfo.  # noqa: E501


        :return: The job_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :rtype: list[object]
        """
        return self._job_accumulators

    @job_accumulators.setter
    def job_accumulators(self, job_accumulators):
        """Sets the job_accumulators of this JobAccumulatorsInfo.


        :param job_accumulators: The job_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :type: list[object]
        """

        self._job_accumulators = job_accumulators

    @property
    def user_task_accumulators(self):
        """Gets the user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501


        :return: The user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :rtype: list[UserTaskAccumulator]
        """
        return self._user_task_accumulators

    @user_task_accumulators.setter
    def user_task_accumulators(self, user_task_accumulators):
        """Sets the user_task_accumulators of this JobAccumulatorsInfo.


        :param user_task_accumulators: The user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :type: list[UserTaskAccumulator]
        """

        self._user_task_accumulators = user_task_accumulators

    @property
    def serialized_user_task_accumulators(self):
        """Gets the serialized_user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501


        :return: The serialized_user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._serialized_user_task_accumulators

    @serialized_user_task_accumulators.setter
    def serialized_user_task_accumulators(self, serialized_user_task_accumulators):
        """Sets the serialized_user_task_accumulators of this JobAccumulatorsInfo.


        :param serialized_user_task_accumulators: The serialized_user_task_accumulators of this JobAccumulatorsInfo.  # noqa: E501
        :type: dict(str, object)
        """

        self._serialized_user_task_accumulators = serialized_user_task_accumulators

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobAccumulatorsInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobAccumulatorsInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
