# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RestoredCheckpointStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'restore_timestamp': 'int',
        'is_savepoint': 'bool',
        'external_path': 'str'
    }

    attribute_map = {
        'id': 'id',
        'restore_timestamp': 'restore_timestamp',
        'is_savepoint': 'is_savepoint',
        'external_path': 'external_path'
    }

    def __init__(self, id=None, restore_timestamp=None, is_savepoint=None, external_path=None):  # noqa: E501
        """RestoredCheckpointStatistics - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._restore_timestamp = None
        self._is_savepoint = None
        self._external_path = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if restore_timestamp is not None:
            self.restore_timestamp = restore_timestamp
        if is_savepoint is not None:
            self.is_savepoint = is_savepoint
        if external_path is not None:
            self.external_path = external_path

    @property
    def id(self):
        """Gets the id of this RestoredCheckpointStatistics.  # noqa: E501


        :return: The id of this RestoredCheckpointStatistics.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RestoredCheckpointStatistics.


        :param id: The id of this RestoredCheckpointStatistics.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def restore_timestamp(self):
        """Gets the restore_timestamp of this RestoredCheckpointStatistics.  # noqa: E501


        :return: The restore_timestamp of this RestoredCheckpointStatistics.  # noqa: E501
        :rtype: int
        """
        return self._restore_timestamp

    @restore_timestamp.setter
    def restore_timestamp(self, restore_timestamp):
        """Sets the restore_timestamp of this RestoredCheckpointStatistics.


        :param restore_timestamp: The restore_timestamp of this RestoredCheckpointStatistics.  # noqa: E501
        :type: int
        """

        self._restore_timestamp = restore_timestamp

    @property
    def is_savepoint(self):
        """Gets the is_savepoint of this RestoredCheckpointStatistics.  # noqa: E501


        :return: The is_savepoint of this RestoredCheckpointStatistics.  # noqa: E501
        :rtype: bool
        """
        return self._is_savepoint

    @is_savepoint.setter
    def is_savepoint(self, is_savepoint):
        """Sets the is_savepoint of this RestoredCheckpointStatistics.


        :param is_savepoint: The is_savepoint of this RestoredCheckpointStatistics.  # noqa: E501
        :type: bool
        """

        self._is_savepoint = is_savepoint

    @property
    def external_path(self):
        """Gets the external_path of this RestoredCheckpointStatistics.  # noqa: E501


        :return: The external_path of this RestoredCheckpointStatistics.  # noqa: E501
        :rtype: str
        """
        return self._external_path

    @external_path.setter
    def external_path(self, external_path):
        """Sets the external_path of this RestoredCheckpointStatistics.


        :param external_path: The external_path of this RestoredCheckpointStatistics.  # noqa: E501
        :type: str
        """

        self._external_path = external_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RestoredCheckpointStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RestoredCheckpointStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
