# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SubtaskAccumulatorsInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subtask': 'int',
        'attempt': 'int',
        'host': 'str',
        'user_accumulators': 'list[UserAccumulator]'
    }

    attribute_map = {
        'subtask': 'subtask',
        'attempt': 'attempt',
        'host': 'host',
        'user_accumulators': 'user-accumulators'
    }

    def __init__(self, subtask=None, attempt=None, host=None, user_accumulators=None):  # noqa: E501
        """SubtaskAccumulatorsInfo - a model defined in Swagger"""  # noqa: E501
        self._subtask = None
        self._attempt = None
        self._host = None
        self._user_accumulators = None
        self.discriminator = None
        if subtask is not None:
            self.subtask = subtask
        if attempt is not None:
            self.attempt = attempt
        if host is not None:
            self.host = host
        if user_accumulators is not None:
            self.user_accumulators = user_accumulators

    @property
    def subtask(self):
        """Gets the subtask of this SubtaskAccumulatorsInfo.  # noqa: E501


        :return: The subtask of this SubtaskAccumulatorsInfo.  # noqa: E501
        :rtype: int
        """
        return self._subtask

    @subtask.setter
    def subtask(self, subtask):
        """Sets the subtask of this SubtaskAccumulatorsInfo.


        :param subtask: The subtask of this SubtaskAccumulatorsInfo.  # noqa: E501
        :type: int
        """

        self._subtask = subtask

    @property
    def attempt(self):
        """Gets the attempt of this SubtaskAccumulatorsInfo.  # noqa: E501


        :return: The attempt of this SubtaskAccumulatorsInfo.  # noqa: E501
        :rtype: int
        """
        return self._attempt

    @attempt.setter
    def attempt(self, attempt):
        """Sets the attempt of this SubtaskAccumulatorsInfo.


        :param attempt: The attempt of this SubtaskAccumulatorsInfo.  # noqa: E501
        :type: int
        """

        self._attempt = attempt

    @property
    def host(self):
        """Gets the host of this SubtaskAccumulatorsInfo.  # noqa: E501


        :return: The host of this SubtaskAccumulatorsInfo.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this SubtaskAccumulatorsInfo.


        :param host: The host of this SubtaskAccumulatorsInfo.  # noqa: E501
        :type: str
        """

        self._host = host

    @property
    def user_accumulators(self):
        """Gets the user_accumulators of this SubtaskAccumulatorsInfo.  # noqa: E501


        :return: The user_accumulators of this SubtaskAccumulatorsInfo.  # noqa: E501
        :rtype: list[UserAccumulator]
        """
        return self._user_accumulators

    @user_accumulators.setter
    def user_accumulators(self, user_accumulators):
        """Sets the user_accumulators of this SubtaskAccumulatorsInfo.


        :param user_accumulators: The user_accumulators of this SubtaskAccumulatorsInfo.  # noqa: E501
        :type: list[UserAccumulator]
        """

        self._user_accumulators = user_accumulators

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubtaskAccumulatorsInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubtaskAccumulatorsInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
