# coding: utf-8

"""
    Flink API Client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TaskManagersInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'taskmanagers': 'list[TaskManagerInfo]'
    }

    attribute_map = {
        'taskmanagers': 'taskmanagers'
    }

    def __init__(self, taskmanagers=None):  # noqa: E501
        """TaskManagersInfo - a model defined in Swagger"""  # noqa: E501
        self._taskmanagers = None
        self.discriminator = None
        if taskmanagers is not None:
            self.taskmanagers = taskmanagers

    @property
    def taskmanagers(self):
        """Gets the taskmanagers of this TaskManagersInfo.  # noqa: E501


        :return: The taskmanagers of this TaskManagersInfo.  # noqa: E501
        :rtype: list[TaskManagerInfo]
        """
        return self._taskmanagers

    @taskmanagers.setter
    def taskmanagers(self, taskmanagers):
        """Sets the taskmanagers of this TaskManagersInfo.


        :param taskmanagers: The taskmanagers of this TaskManagersInfo.  # noqa: E501
        :type: list[TaskManagerInfo]
        """

        self._taskmanagers = taskmanagers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskManagersInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskManagersInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
